spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/aicart?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true  # ← 이거 추가
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always